version: "3.9"

services:
  mongo:
    image: mongo:8.2
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: devconnect
      MONGO_INITDB_ROOT_USERNAME: mongoUser
      MONGO_INITDB_ROOT_PASSWORD: mongoPass123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dev-connect
  minio:
    image: minio/minio:latest
    container_name: devconnect-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - dev-connect
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devconnect-storage-api
    depends_on:
      - mongo
      - minio
    environment:
      PORT: 8083
      MONGO_URI: "mongodb://mongoUser:mongoPass123@mongo:27017/devconnect?authSource=admin"
      MONGO_DB: "devconnect"
      MONGO_COLLECTION: "files"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_USER: "minioadmin"
      MINIO_PASSWORD: "minioadmin"
      MINIO_BUCKET: "test-bucket"
      MINIO_USE_SSL: "false"
      AUTH_URI: http://devconnect:8080
    ports:
      - "8083:8083"
    networks:
      - dev-connect
volumes:
  mongo-data:
  minio-data:


networks:
  dev-connect:
    external: true